### ISSUE TITLE
Gateway crash if InfluxDb is unreachable

### ISSUE THREAD

**Issue by trizmark** [NoWiresGB/RFM69GwToInfluxBridge#22]
Logs showing the issue:

```
Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn

    conn = connection.create_connection(

  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection

    raise err

  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen

    httplib_response = self._make_request(

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request

    conn.request(method, url, **httplib_request_kw)

  File "/usr/lib/python3.8/http/client.py", line 1255, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output

    self.send(msg)

  File "/usr/lib/python3.8/http/client.py", line 950, in send

    self.connect()

  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect

    conn = self._new_conn()

  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn

    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7607fb20>: Failed to establish a new connection: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen

    retries = retries.increment(

  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.0.200', port=8086): Max retries exceeded with url: /write?db=home_iot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7607fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/bin/RFM69GwToInfluxBridge.py", line 329, in <module>

    main()

  File "/bin/RFM69GwToInfluxBridge.py", line 300, in main

    mqtt_client.loop_forever()

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever

    rc = self.loop(timeout, max_packets)

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop

    rc = self.loop_read(max_packets)

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read

    rc = self._packet_read()

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read

    rc = self._packet_handle()

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle

    return self._handle_publish()

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish

    self._handle_on_message(message)

  File "/usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message

    self.on_message(self, self._userdata, message)

  File "/bin/RFM69GwToInfluxBridge.py", line 149, in on_message

    _send_sensor_data_to_influxdb(measurements)

  File "/bin/RFM69GwToInfluxBridge.py", line 273, in _send_sensor_data_to_influxdb

    influxClient.write_points(json_body)

  File "/usr/lib/python3.8/site-packages/influxdb/client.py", line 603, in write_points

    return self._write_points(points=points,

  File "/usr/lib/python3.8/site-packages/influxdb/client.py", line 681, in _write_points

    self.write(

  File "/usr/lib/python3.8/site-packages/influxdb/client.py", line 413, in write

    self.request(

  File "/usr/lib/python3.8/site-packages/influxdb/client.py", line 332, in request

    response = self._session.request(

  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send

    r = adapter.send(request, **kwargs)

  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.0.200', port=8086): Max retries exceeded with url: /write?db=home_iot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7607fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by trizmark** [comment]
Startup loop tested successfully - now just need to test the in-flight database connectivity loss.
